## Barbaro, Kurella, Roth: Electoral outcomes versus voters' preferences: on the different tales the data can tell. JoEPOP 2026
## Short-Term (2021) Analysis
library(ggplot2)
library(tidyr)
library(dplyr)
library(hutils)
library(ggpubr)
library(reshape2)
library(forcats)
library(lubridate)
library(foreach)
library(doParallel)
nbcores <- detectCores() - 2
### load the files generated by BKR01_Data2021.R
#
## Borda Seat Shares
seatshare.fun <- function(w){
  wave <- ranking.w %>% filter(., V5 == w) %>% 
    mutate(across(where(is.character), as.numeric)) %>%
    mutate(bs.u = 6 -  UNION, bs.s = 6 - SPD, bs.a = 6 - AFD, bs.f = 6 - FDP, bs.l = 6 - LINKE, bs.g = 6 - GREEN )
  crosssum <-  (sum(wave$bs.u) + sum(wave$bs.s) + 
                  sum(wave$bs.a) + sum(wave$bs.f) + 
                  sum(wave$bs.l) + sum(wave$bs.g))
  seatshares <- c(sum(wave$bs.u) / crosssum, sum(wave$bs.s) / crosssum, sum(wave$bs.a) / crosssum,
                  sum(wave$bs.f) / crosssum, sum(wave$bs.l) / crosssum, sum(wave$bs.g) / crosssum)
  return(seatshares)
}
# Wave Lists
wave.list <- as.list(unique(za7856$V5 ))
wave.list.short <- wave.list[-c(18, 19, 20, 21, 22)]
# Seat Distribution by Borda's rule
borda.seats.list <- mclapply(wave.list.short, seatshare.fun, mc.cores = nbcores) %>% 
  do.call(rbind, .) %>% as.data.frame(.) %>% setNames(colnames(ranking.w)[1:6]) %>% 
  mutate(wave = 1:17) 
#
# Seat Distribution by plurality-based PR
btwpolls <- read.csv(url("https://gitlab.rlp.net/sbarbaro/btw21/-/raw/main/btwpolls.csv?inline=false")) %>%
  mutate(Datum = dmy(Datum)) %>% rename(Date = Datum) %>% 
  select(-c("ErhebZeitraum", "Participants"))  %>%
  melt(., id.vars = c("Date")) %>% 
  filter(., Date > "2021-01-01" & Date < "2021-09-25") %>%
  left_join(x = ., y = data.frame(Date = sort(unique(.$Date)), wave = 1:17), by = "Date")
##########################################################################################
## Figures (Fig. 2 in the paper)
pr21.pic <- ggplot(data = btwpolls,
       aes(x = wave, y = value, group = variable, colour = variable)) +
  scale_y_continuous(labels = scales::percent, limits = c(0,.40)) +
  geom_line(linewidth = 1) + 
  theme_bw(base_size = 22) +
  scale_colour_manual(values=c(AFD = "chocolate", FDP = "yellow2", 
                               GREEN = "forestgreen", LINKE = "violet",
                               SPD = "red", UNION = "black"),
                      limits = c("UNION", "SPD", "GREEN", "FDP", "LINKE", "AFD")) +
  labs(col = "Party", x = "Wave", y = "Seat Shares under PR")

bordaseats.pic <- 
  ggplot(data = borda.seats.list %>% melt(., id.vars = "wave"),
         aes(x = wave, y = value, group = variable, colour = variable)) +
  geom_line(linewidth = 1) + 
  scale_y_continuous(labels = scales::percent, limits = c(0,.40)) +
  scale_colour_manual(values=c(AFD = "chocolate", FDP = "yellow2", 
                               GREEN = "forestgreen", LINKE = "violet",
                               SPD = "red", UNION = "black")) +
  theme_bw(base_size = 22) + labs(y = "Seat Shares by Borda Scores", col = "party", x = "Wave")  
##
Fig2 <- ggarrange(pr21.pic, bordaseats.pic, ncol = 2, 
                  common.legend = T, legend = "bottom")
Fig2
ggsave("PluralityBorda3.pdf", 
       width = 16, height = 9, plot = Fig2)


### Fig2 in transparent for presentation purposes
pr21.pic <- ggplot(data = btwpolls,
                   aes(x = wave, y = value, group = variable, colour = variable)) +
  scale_y_continuous(labels = scales::percent, limits = c(0,.40)) +
  geom_line(linewidth = 1) + 
  theme_bw(base_size = 22) +
  theme(legend.position = "none",
        axis.text.x = element_text(color = "#C1002B"),  # Rotate and color x-axis labels #C1002B
        axis.text.y = element_text(color = "#C1002B"),                         # Color y-axis labels #C1002B
        axis.title.x = element_text(color = "#C1002B"),                        # Color x-axis title #C1002B
        axis.title.y = element_text(color = "#C1002B"),                        # Color y-axis title #C1002B
        legend.title = element_text(color = "#C1002B"),                        # Color legend title #C1002B
        legend.text = element_text(color = "#C1002B"),                         # Color legend text #C1002B
        legend.background = element_rect(fill = "transparent", color = NA),
        plot.background = element_rect(fill = "transparent", color = NA),      # Transparent plot background
        panel.background = element_rect(fill = "transparent", color = NA),     # Transparent panel background                                # Remove minor gridlines
        panel.grid.major = element_line(color = "gray80"),                      # White major gridlines
        panel.grid.minor = element_line(color = "gray80")  
  ) +
  scale_colour_manual(values=c(AFD = "chocolate", FDP = "yellow2", 
                               GREEN = "forestgreen", LINKE = "violet",
                               SPD = "red", UNION = "black"),
                      limits = c("UNION", "SPD", "GREEN", "FDP", "LINKE", "AFD")) +
  labs(col = "Party", x = "Wave", y = "Seat Shares under PR")

bordaseats.pic <- 
  ggplot(data = borda.seats.list %>% melt(., id.vars = "wave"),
         aes(x = wave, y = value, group = variable, colour = variable)) +
  geom_line(linewidth = 1) + 
  scale_y_continuous(labels = scales::percent, limits = c(0,.40)) +
  scale_colour_manual(values=c(AFD = "chocolate", FDP = "yellow2", 
                               GREEN = "forestgreen", LINKE = "violet",
                               SPD = "red", UNION = "black")) +
  theme_bw(base_size = 22) +
  theme(legend.position = "none",
        axis.text.x = element_text(color = "#C1002B"),  # Rotate and color x-axis labels #C1002B
        axis.text.y = element_text(color = "#C1002B"),                         # Color y-axis labels #C1002B
        axis.title.x = element_text(color = "#C1002B"),                        # Color x-axis title #C1002B
        axis.title.y = element_text(color = "#C1002B"),                        # Color y-axis title #C1002B
        legend.title = element_text(color = "#C1002B"),                        # Color legend title #C1002B
        legend.text = element_text(color = "#C1002B"),                         # Color legend text #C1002B
        legend.background = element_rect(fill = "transparent", color = NA),
        plot.background = element_rect(fill = "transparent", color = NA),      # Transparent plot background
        panel.background = element_rect(fill = "transparent", color = NA),     # Transparent panel background                                # Remove minor gridlines
        panel.grid.major = element_line(color = "gray80"),                      # White major gridlines
        panel.grid.minor = element_line(color = "gray80")  
  ) +
  labs(y = "Seat Shares by Borda Scores", col = "party", x = "Wave")  

Fig2 <- ggarrange(pr21.pic, bordaseats.pic, ncol = 2, 
                  common.legend = T, legend = "right")
Fig2
ggsave("PluralityBordaT.pdf", 
       width = 16, height = 8, plot = Fig2)

