## Barbaro, Kurella, Roth: Electoral outcomes versus voters' preferences: on the different tales the data can tell. JoEPOP 2026
## Short-Term (2021) Analysis
library(ggplot2)
library(tidyr)
library(dplyr)
library(hutils)
library(ggpubr)
library(forcats)
library(lubridate)
library(labelled)
library(foreach)
library(doParallel)
nbcores <- detectCores() - 2
### load the files generated by BKR01_Data2021.R
#load("BKR01_Data2021.RData")
load(url("https://gitlab.rlp.net/sbarbaro/aggregationrule/-/raw/main/BKR01_Data2021.RData?inline=false"))
#
plot.data <- za.w.df %>% filter(.,V5 %in% 1:38) %>%
  mutate(V5neu = as.factor(V5)) %>%
  select(., c("V5neu", "V50.UNI", "V52", "V53", "V54", "V55", "V56")) %>%
  rename(UNION = "V50.UNI", SPD = "V52", AFD = "V53", FDP = "V54", LINKE = "V55", GREEN = "V56") %>%
  mutate(UNION = UNION - 6, SPD = SPD - 6, AFD = AFD - 6, FDP = FDP -6, LINKE = LINKE - 6, GREEN = GREEN - 6) %>%
  left_join(x = ., y = data.frame(V5neu = sort(unique(.$V5neu)), Wave = as.factor(1:16)), by = "V5neu") %>%
  melt(., id.vars = c("V5neu", "Wave")) %>%
  left_join(x = ., 
            y = data.frame(variable = unique(.$variable), 
                           colfill = c("black", "red", "chocolate", 
                                       "yellow2", "violet", "forestgreen")), by = "variable")
#
plot.fun <- function(p){
  ggplot(data = plot.data %>% filter(., variable %in% p), 
         aes(y = value, x = Wave, colour = Wave, group = Wave ) ) +
    geom_boxplot(outlier.size = 0, 
                 col = as.character(plot.data %>% 
                                      filter(., variable %in% p) %>% 
                                      select("colfill") %>% slice(1)), 
                 alpha = 0.3,
                 fill = as.character(plot.data %>% 
                                       filter(., variable %in% p) %>% 
                                       select("colfill") %>% slice(1)) ) + 
    theme_gray(base_size = 20) + theme(legend.position = "none") +
    labs(subtitle = p, y = "", x = "Wave")
}
### 
party.list = list("UNION", "SPD", "GREEN", "FDP", "LINKE",  "AFD")

plots <- mclapply(party.list, plot.fun, mc.cores = nbcores)
Fig3 <- ggarrange(plotlist = plots, ncol = 2, nrow = 3)
Fig3
ggsave("boxplots2021.pdf", width = 16, height = 9, plot = Fig3)
